/**
 * Field length limits
 */
export const LIMITS = {
  // User fields
  EMAIL_MAX_LENGTH: 255,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  FIRST_NAME_MIN_LENGTH: 2,
  FIRST_NAME_MAX_LENGTH: 100,
  LAST_NAME_MIN_LENGTH: 2,
  LAST_NAME_MAX_LENGTH: 100,
  PHONE_MAX_LENGTH: 20,

  // Address fields
  STREET_MAX_LENGTH: 255,
  CITY_MAX_LENGTH: 100,
  PROVINCE_MAX_LENGTH: 100,
  POSTAL_CODE_MAX_LENGTH: 20,
  COUNTRY_CODE_LENGTH: 2,

  // Medical fields
  ALLERGY_MAX_LENGTH: 100,
  ALLERGY_MAX_COUNT: 50,
  CONDITION_MAX_LENGTH: 200,
  CONDITION_MAX_COUNT: 50,
  MEDICATION_NAME_MAX_LENGTH: 200,
  DIAGNOSIS_MAX_LENGTH: 500,

  // Content fields
  NOTES_MAX_LENGTH: 5000,
  DESCRIPTION_MAX_LENGTH: 2000,
  SHORT_DESCRIPTION_MAX_LENGTH:  500,
  REASON_MAX_LENGTH: 500,

  // Reference numbers
  PATIENT_NUMBER_LENGTH: 12,
  APPOINTMENT_NUMBER_LENGTH: 14,
  PRESCRIPTION_NUMBER_LENGTH: 14,

  // Emergency contacts
  EMERGENCY_CONTACTS_MIN:  2,
  EMERGENCY_CONTACTS_MAX: 5,

  // Arrays
  MAX_ARRAY_ITEMS: 100,
} as const;
